### ISSUE TITLE
Router Table Support in NGINX

### ISSUE THREAD

**Issue by willcode4food** [rstudio/redx#26]
I saw this enhancement request on hipache's repo [https://github.com/hipache/hipache/issues/20](url)

I was wondering since NGINX is being used,  would Redx support URL rewriting? Or is this something a plugin could be used to solve?

**Comment by CBarraford** [comment]
As i read that hipache issue, it sounds like they just want to route a certain path to a certain server. Redx does this out of the box (not special nginx configs or additional plugins).

This would be done by setting up backends (in the hipache example) for each "route". Then frontends that match to a specific backend 

Does that make sense?

**Comment by willcode4food** [comment]
yes it does.  Thank you so much.
